architectureType: sklearn
categoricalFeatureNames:
  - Gender
  - Geography
classNames:
  - Retained
  - Exited
featureNames:
  - CreditScore
  - Geography
  - Gender
  - Age
  - Tenure
  - Balance
  - NumOfProducts
  - HasCrCard
  - IsActiveMember
  - EstimatedSalary
metadata:
  test: name
modelType: full
name: Churn prediction model
